name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_IMAGE: henamorado/hello-world-node
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE

    - name: Set up Azure CLI
      uses: azure/cli@v1
      with:
        azcliversion: 2.0.72

    - name: Login to Azure Container Registry
      run: |
        az acr login --name containerregistrystudy

    - name: Tag and Push Docker Image to Azure Container Registry
      env:
        AZURE_REGISTRY: containerregistrystudy.azurecr.io
      run: |
        docker tag $DOCKER_IMAGE $AZURE_REGISTRY/$DOCKER_IMAGE
        docker push $AZURE_REGISTRY/$DOCKER_IMAGE



