name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      env:
        DOCKER_USERNAME: henamorado
        DOCKER_PASSWORD: DemonHunter.860316
        DOCKER_IMAGE: henamorado/hello-world-node
      run: |
        docker buildx create --use
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE .
        docker push $DOCKER_IMAGE

